AURORA-149: Add python checkstyle hooks.
Consolidates python checks into build-support/python.

Adds checkstyle tool, which runs pep8, pyflakes and a number of general code
cleanliness plugins.

Bugs closed: AURORA-149

Reviewed at https://reviews.apache.org/r/21402/

diff --git a/build-support/hooks/pre-commit b/build-support/hooks/pre-commit
--- a/build-support/hooks/pre-commit
+++ b/build-support/hooks/pre-commit
@@ -22,12 +22,12 @@ fi
 HERE=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)
 
 echo "Performing Python import order check."
-if ! $HERE/../../build-support/isort-check >&/dev/null; then
+if ! $HERE/../../build-support/python/isort-check >&/dev/null; then
   echo ""
   echo ""
   echo "** PYTHON IMPORT ORDER CHECK FAILED"
   echo "*"
-  echo "* please run: build-support/isort-run"
+  echo "* please run: build-support/python/isort-run"
   echo "*"
   echo "**"
   echo ""
@@ -36,3 +36,17 @@ else
   echo "SUCCESS"
 fi
 
+echo "Performing Python checkstyle."
+if ! $HERE/../../build-support/python/checkstyle-check >&/dev/null; then
+  echo ""
+  echo ""
+  echo "** PYTHON CHECKSTYLE FAILED"
+  echo "*"
+  echo "* For more information please run: build-support/python/checkstyle-check"
+  echo "*"
+  echo "**"
+  echo ""
+  exit 1
+else
+  echo "SUCCESS"
+fi
